# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Notes of a Java developer
tagline:	'blog'
description:	'Notes of a Java developer'
url:		http://bdulac.github.io/

author:
  name:		'Bérenger Dulac'
  url:		http://bdulac.github.io/

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.png

social:
  - icon:	facebook
    url:	http://facebook.com/berenger.dulac
    desc:	Join me on Facebook

  - icon:	github
    url:	https://github.com/bdulac
    desc:	Fork me on github

  - icon:	feed
    url:	http://bdulac.github.io/atom.xml
    desc:	Subscribe to my Atom feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Bérenger Dulac
  url:		https://github.com/bdulac
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
